# Copyright 2023 ETH Zurich and the QuaTrEx authors. All rights reserved.

# Path to the system-matrices
#   path_to_hamiltonian: str = path to the Hamiltonian matrix
#   path_to_overlap_matrix: str = path to the overlap matrix
#   path_to_coulomb_matrix: str = path to the Coulomb matrix
#
#   The system-matrices are given in complex-number float128 binary format.
path_to_hamiltonian = "data/hamiltonian.bin"
path_to_overlap_matrix = "data/overlap_matrix.bin"
path_to_coulom_matrix = "data/coulomb_matrix.bin"

# Blocksize of the system-matrices
#   blocksize: int 
blocksize = 1

# Path to the atoms positions and the position per orbitals matrices.
#   path_to_atoms_positions: str = path to the atoms positions
#   path_to_position_per_orbitals: str = path to the position per orbitals
#
#   The atoms positions and positions per orbitals are given in the xyz format. 
#   If atoms positions are given, intern function will deduce the position per
#   orbitals from the atoms positions.
path_to_atoms_positions = "data/atoms_positions.xyz"
path_to_position_per_orbitals = "data/position_per_orbitals.yaml"

# Conduction band energy [eV]
#   conduction_band_energy: float
conduction_band_energy = 1

# Temperature in Kelvin [K]
#   temperature: float
temperature = 300

# Solver solver
#   solver_mode: str
#       - "gf" for Green's Function computation
#       - "gw" for electron-electron GW computation
solver_mode = "gw"

# Energy grid
#   start_energy: float = start of the energy range [eV]
#   end_energy: float = end of the energy range [eV]
#   energy_step: float = energy step of the grid [eV]
#
#   The energy array will be computed using the left energy range and the
#   energy step. Stepping up to the right energy range.
[energy_grid]
start_energy = 0
end_energy = 1
energy_step = 0.1

# Fermi levels
#  left_fermi_level: float = Fermi level of the left electrode [eV]
#  right_fermi_level: float = Fermi level of the right electrode [eV]
#  applied_voltage: float = applied voltage [V]
#
#  Data validation will be performed to ensure that the given fermi levels
#  and applied voltage are consistent with each other. If one is set to "None",
#  it will be computed from the other two.
[fermi_levels]
left_fermi_level = 1
right_fermi_level = 0.5
applied_voltage = 0.5
